---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: front
  labels:
    app: front
    sandbox: learn-kubernetes
    learn-kubernetes: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: docker.io/jamp1992/front:front
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: front-external
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
  - name: http
    port: 8080
    targetPort: 8080
